### ISSUE TITLE
Present related links gathered from relationship tables

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/oxygen-dita-outgoing-references-view#16]
In Oxygen 22 we'll try to implement a new API method:

ro.sync.ecss.dita.DITAAccess.getRelatedLinksFromReltable(URL)

      /**
       * Get the list of related links from all the relationship tables defined in the DITA Maps.
       * @param originatorURL The topic for which we are searching for outgoing links.
       * 
       * @return The list of related links from all the relationship tables defined in the DITA Maps.
       * 
       * @since 22
       */
      public static List<RelLink> getRelatedLinksFromReltable(URL originatorURL){

The RelLink interface:

      public interface RelLink {
        
        /**
         * @return Returns the source URL.
         */
        public URL getSourceURL();
        
        /**
         * @return Returns the target URL.
         */
        public URL getTargetURL();
        
        /**
         * @return Returns the target definition location.
         */
        public URL getTargetDefinitionLocation();
      }

We need to show in the side view also the related links from the topic to other targets.

**Comment by raducoravu** [comment]
Example of how reltables are used in DITA Maps in order to establish relationships between topics:

https://www.oxygenxml.com/dita/1.3/specs/langRef/base/reltable.html

**Comment by raducoravu** [comment]
So in the example above if I open "batsonar.dita" in the editor and I have the DITA Map opened in the DITA Maps Manager view, the side view should show related links to "    batcaring.dita, batfeeding.dita, batguano.dita, bathistory.dita".

**Comment by alexdinisor98** [comment]
Fixed test https://github.com/oxygenxml/oxygen-dita-outgoing-references-view/commit/fe46f1bde3b988703f686295a11b5048b4e2be19
