### ISSUE TITLE
Perhaps also present audio and video references

### ISSUE THREAD

**Issue by sorincarbunaru** [oxygenxml/oxygen-dita-outgoing-references-view#22]
If you have references to audio or video files in you topic, you might want to see them listed in the side-view, as you see the images.

**Comment by raducoravu** [comment]
👍

**Comment by raducoravu** [comment]
Work was completed on commit: https://github.com/oxygenxml/oxygen-dita-outgoing-references-view/commit/434c4e15ddce6cd79f1ae085f4e10a5f44ba488a
