### ISSUE TITLE
Take profiling condition sets into account when rendering the references in the tree

### ISSUE THREAD

**Issue by sorincarbunaru** [oxygenxml/oxygen-dita-outgoing-references-view#23]
When applying a profiling condition set in oXygen, certain parts of content can become hidden or grayed-out.

It would be probably a good idea to also mark the excluded content in the references tree. The best approach would probably be to make the nodes grayed-out (even if the excluded content is hidden).

**Comment by raducoravu** [comment]
We would probably need new API for this on the Oxygen side.

**Comment by raducoravu** [comment]
Will not implement this for now.
