### ISSUE TITLE
Special mode in which incoming references to the topic are presented

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/oxygen-dita-outgoing-references-view#28]
We would need some special API on the Oxygen side to call and see all incoming references to the current opened topic, then present these references in the side view. In this way the side view would have two modes: Outgoing and Incoming

**Comment by raducoravu** [comment]
I opened issue with ID EXM-44084 on the Oxygen side.

**Comment by raducoravu** [comment]
+1 stan.doherty@oracle.com

> The "DITA References" add-on is fabulous for interrogating outbound refeences from the current topic.

> The "Search References" function from the DITA Maps Manager does a great job in locating inbound references to the currentlky selected <topicref>.

> What are the chances that some version of  "DITA References" would allow me to view either inbound or outbound references? The writers I support like the add-on interface -- not so much the message-formatted output.

**Comment by sorincarbunaru** [comment]
+1 https://www.oxygenxml.com/forum/posting.php?mode=reply&f=2&t=21719#pr58981

**Comment by sorincarbunaru** [comment]
+1 tot pe https://www.oxygenxml.com/forum/viewtopic.php?p=59260#p59260, de la Chris Papademetrious (Synopys)

**Comment by sorincarbunaru** [comment]
It seems that people would like to see the outgoing and the incoming references simultaneously.

**Comment by jhanna-pasco** [comment]
+1 I would also like to add my desire to see an incoming references feature added.

**Comment by raducoravu** [comment]
@jhanna-pasco thanks for the vote, we'll take this into account. I hope we'll be able to work a bit on this feature in the next months.

**Comment by raducoravu** [comment]
The "incoming" references presenter panel would use API methods which will only be available in Oxygen 23. But the plugin needs to remain compatible with older Oxygen versions, so the API methods: "ro.sync.ecss.dita.DITAAccess.createReferencesGraph()" and "ro.sync.ecss.dita.DITAAccess.searchReferences(URL, Object)" need to be called using Java reflection. If the methods do not exist, then the "Incoming/Outgoing" switches are not shown anymore.

The method "DITAAccess.createReferencesGraph()" may take a long time to return so it needs to be called on a thread, and the panel should be updated after the method finishes. We also need a manual action in the side view to refresh the references graph because it does not update automatically when content is edited and extra references are made.

The incoming references presenter would present a tree of incoming references. The first level in the tree presents all maps and topics which have references to this current opened topic. For each of them we present the file name, the tooltip presenting the absolute reference to it. You can use the API "ro.sync.exml.workspace.api.util.UtilAccess.getFileName(String)" to get the file name of the URL. You can use the API "ro.sync.basic.util.URLUtil.getDescription(String)" to obtain the absolute path to the URL with credentials removed from it.

When I double click a reference Oxygen opens the reference file at the precise location where the reference is located. A DocumentPositionedInfo object has line and column information and you can use that information on the URL which is opened to instruct Oxygen to move the caret to that location: https://www.oxygenxml.com/doc/versions/21.1/ug-editor/topics/opening-document-from-cli.html

The first level of references can also be expanded, each time a reference is expanded in the tree model you can call "DITAAccess.searchReferences" on it and present in the tree the results showing from where that reference is referenced in its turn.

**Comment by raducoravu** [comment]
You can use the API:
ro.sync.exml.workspace.api.images.ImageUtilitiesSpecificProvider.getIconDecoration(URL)
to obtain a small icon to display next to each reference file in the tree.

**Comment by raducoravu** [comment]
Some feedback after working with current implementation:

 1. The Refresh action needs to be done somehow on a thread or a timer task because now it blocks the entire user interface probably while the references graph is computed
 1. When I double click an Incoming reference there are two actions which are done, you open the topic which has the reference and the node is expanded in the tree. It's confusing to produce two effects with the same action. Maybe you can avoid expanding nodes in the JTree by double click, like we do for the DITA Maps manager view.
 1. Maybe a contextual menu would be useful containing an action to "Open reference" similar to what you do for Enter and mouse dbl click.
 1. When I double click a reference, the reference topic is opened in Oxygen, initially I see you also select the entire reference element but then I see the selection is removed.
 1. Maybe the presented references should be sorted by file name in order to have some kind of order.
 1. Sometimes we list the same topic multiple times in the Incoming list (because that topic refers to this current topic multiple times). I'm not sure if we could make this representation more compact somehow.

<img width="304" alt="Screen Shot 2020-11-05 at 9 55 19 AM" src="https://user-images.githubusercontent.com/1005979/98212970-0c0c2f00-1f4d-11eb-9423-6e261ea843cd.png">

**Comment by raducoravu** [comment]
You can probably close this issue as well and afterwards update the readme on the project.
