### ISSUE TITLE
Try to remove all sonar problems

### ISSUE THREAD

**Issue by mmmmmcr** [oxygenxml/oxygen-dita-outgoing-references-view#33]
https://sonarcloud.io/organizations/oxygenxml-github/projects

**Comment by mmmmmcr** [comment]
cd2d8a58d96b32dce71a00a992c60acb69b67656
18882241bd15bfeb5e721a724d9692e3289566bf
89be291280e001148088b598741b0574819ea6bc
9705f9f1d00bf6bb31614a0d06d9f65d4153bdaf

**Comment by raducoravu** [comment]
Code review la code review:

The field "com.oxygenxml.ditareferences.tree.references.incoming.IncomingReference.translator" should be static and private.
Cand avem if-uri in "com.oxygenxml.ditareferences.tree.references.incoming.IncomingReference.equals(Object)" trebuie sa punem si brackets, chiar daca nu este decat o linie de cod in if.
com.oxygenxml.ditareferences.tree.references.incoming.IncomingReferencesPanel.translator => can be static. In fact all places where the translator is instantiated, it can be used there as a static final field I think.

"com.oxygenxml.ditareferences.workspace.rellinks.RelLinksAccessor.getRelationshipTableTargetURLs(URL)" why do you use the "forTests" both on the If and the else clauses? Why not use only the code which is on the else clause?

Why is the "com.oxygenxml.ditareferences.i18n.DITAReferencesTranslator" declared as serializable?

Here "com.oxygenxml.ditareferences.tree.references.outgoing.OpenReferenceAction.actionPerformed(ActionEvent)" all the if clauses related to keyref, conkeyref, datakeyref 

com.oxygenxml.ditareferences.workspace.StringUtilities.trimNodeText(FontMetrics, String, int) => the negation of "<=" is not ">=".

**Comment by mmmmmcr** [comment]
I don't understand this:
 Here "com.oxygenxml.ditareferences.tree.references.outgoing.OpenReferenceAction.actionPerformed(ActionEvent)" all the if clauses related to keyref, conkeyref, datakeyref

**Comment by raducoravu** [comment]
@mmmmmcr I think I did not finish my idea, I wanted to say that most of the if clauses invoked similar code and probably they could be compressed further somehow, but it does not matter, you can leave the code as it is.
